### ISSUE TITLE
ModuleNotFoundError: No module named 'dpipe'

### ISSUE THREAD

**Issue by supy0001** [aleemsidra/ConvLoRA#3]
How to install dpipe? I tried to pip install dpipe but failed. I'm really interested in lora on conv. Could you please show the requirements?

**Comment by aleemsidra** [comment]
Hi @supy0001! Thank you for pointing out, I have put it in now the main repository. You can install `dpipe` using the following:

```
git clone https://github.com/neuro-ml/deep_pipe.git
cd deep_pipe
git checkout 5c08d5759d51c0731cc636c2866bb3a538ffab7a
pip install -e .
```
